version: "3.3"

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    ports:
      - "8787:80"
    volumes:
      - ./data:/srv
      - ./config:/config
    restart: unless-stopped
