tunnel: file-share-tunnel
credentials-file: /home/panda/.cloudflared/2fbf5e1e-7d20-4d4e-ac7a-fc734d7dd839.json

ingress:
  - hostname: share.tucker.work
    service: http://localhost:8787
  - hostname: files.tucker.work
    service: http://localhost:8787
  - service: http_status:404
